name: example
description: An example app to show the use of Flutter Staggered Animations.
version: 0.0.1

publish_to: none

environment:
  sdk: ">=3.0.0-0.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_staggered_animations:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  all_lint_rules_community: ^0.0.19

flutter:
  uses-material-design: true
