name: flutter_staggered_animations
description: Easily add staggered animations to your ListView, GridView, Column and Row children as shown in Material Design guidelines
version: 1.1.1
homepage: https://github.com/mobiten/flutter_staggered_animations
repository: https://github.com/mobiten/flutter_staggered_animations
issue_tracker: https://github.com/mobiten/flutter_staggered_animations/issues

environment:
  sdk: ">=2.19.4 <3.0.0"

platforms:
  android:
  ios:

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
