name: flutter_staggered_animations
description: Easily add staggered animations to your ListView, GridView, Column and Row children as shown in Material Design guidelines
version: 1.0.0
homepage: https://github.com/mobiten/flutter_staggered_animations
repository: https://github.com/mobiten/flutter_staggered_animations
issue_tracker: https://github.com/mobiten/flutter_staggered_animations/issues

environment:
  sdk: ">=3.0.0-0.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  all_lint_rules_community: ^0.0.19
  flutter_test:
    sdk: flutter
